### ISSUE TITLE
How to handle assets dev/prod?

### ISSUE THREAD

**Issue by ammichael** [MacKentoch/react-redux-graphql-apollo-bootstrap-webpack-starter#2]
Hi there,

I really like your boilerplate. Thanks a lot (:

The only weird thing I've noticed is how prod bundle is done. Where should I put my static files, like images, fonts?

At first I put at public folder, but then noticed that the bundle wasn't loading my assets. Also, I find it really weird that there is a index.html that is static, not copied from root folder in webpack bundle.

Did I missed something?

Thanks

**Comment by MacKentoch** [comment]
Hi @ammichael 

This starter really need to be upgraded (*webpack 1 is outdated for me now...*).

I fixed the production bundle, so that you can even see it working on [github here](https://mackentoch.github.io/react-redux-graphql-apollo-bootstrap-webpack-starter/)

Your assets should be on docs/assets.

NOTE: it seems like Scaphold access config should be changed since it does no more respond.

**Comment by ammichael** [comment]
Hey there @MacKentoch!
I'm going to take a look at the example you linked.

Actually I didn't use Scaphold, but one of my team's graphql server, so I didn't notice that.. but it would be really nice to update this starter. I looked at several starters, and this one is the best I've seen (:

Thanks.

**Comment by MacKentoch** [comment]
Starting to update/refresh this starter.

What I plan:

- react 15.6.x
- react-hot-reload v3
- [redux-devtools extension](https://github.com/zalmoxisus/redux-devtools-extension)
- webpack 2 (maybe 3)
- react-router 4
- a bit flow type (*mode weak: non intrusive and light*)

With a light server 
- simple
- with server side rendering for 1st rendering

I like this setup. 

How does it sound for you?

**Comment by ammichael** [comment]
It sounds awesome (:

I think Webpack 3 would be a better choice. Any reason to choose a older version?

SSR is really nice, btw!

**Comment by MacKentoch** [comment]
No real reason except I did not use webpack3 until now.

But as it is not supposed to be so different than webpack 2.
So be it, I'll go webpack 3 in this starter.

It will be a good warm up before updating all my other starters.

**Comment by MacKentoch** [comment]
I upgraded to:

- [x] react 15.6.x
- [x] react-hot-reload v3
- [x] redux-devtools extension
- [x] webpack 3
- [x] react-router 4
- [x] with a light server
- [ ] with a SSR server

I still use scapold backend but still have a strange unauthorized error.

If it works on your own backend, I would be pleased to be confirmed.

**Comment by ammichael** [comment]
Hi there,

I just tried it here, and I also have problem with graphql connection. Instead of a 401 error, I'm getting a connection refused.

```
OPTIONS http://0.0.0.0:8000/graphql/ net::ERR_CONNECTION_REFUSED
```

But I'm not sure if I forgot to config something, so I'm not sure if this is something with the Apollo config itself, but the boilerplate sure is a lot better (:

Thanks a lot!

**Comment by MacKentoch** [comment]
Thank for sharing.
I remove
I need to figure out this issue.

I suspect something around Apollo.

**Comment by MacKentoch** [comment]
It is fixed.
It was stupid bug...

It should work nice on your side now.

**Comment by ammichael** [comment]
Yeah, worked fine here as well.

Great work @MacKentoch!

Thanks a lot
