### ISSUE TITLE
error in view/pageNotFound file name

### ISSUE THREAD

**Issue by aspanoz** [MacKentoch/react-redux-graphql-apollo-bootstrap-webpack-starter#4]
Fix file naming:
src/app/views/pageNotfound/PageNotfound.js -> src/app/views/pageNotFound/PageNotFound.js

**Comment by MacKentoch** [comment]
Thank you @aspanoz 

It is now fixed.

I added a bonus feature:
- authentication checks if token is expired (*then redirect to login*) to avoid errors when it expires.
